baseURL = "https://kirugan.github.io/"
languageCode = "en-us"
title = "Blog of software wizard"
theme = "axiom"
enableEmoji = true
ignoreFiles = [ "\\.swp$" ]
publishDir = "docs"

[params]
copyrightYear = 2020
